server:
  port: 8181

spring:
  # ?????
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/music?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource

#  # redis??
#  redis:
#    # ?????
#    host: localhost
#    # ??
#    port: 6379
#    # ???
#    database: 0
#    # ?????2000??
#    timeout: 2000ms
#    # ??
#    password:
#    # ??lettuce???
#    lettuce:
#      pool:
#        # ????????8
#        max-active: 5
#        # ?????????????-1
#        max-wait: 10000ms
#        # ?????????8
#        max-idle: 10
#        # ?????????0
#        min-idle: 5




# Mybatis-plus??
mybatis-plus:
  # ??Mapper????
  mapper-locations: classpath*:/mapper/*Mapper.xml
  # ??MyBatis????????????????
  type-aliases-package: com.java.tsd.music
  configuration:
    # ??????
    map-underscore-to-camel-case: false

# Mybatis SQl ?????????????Mapper.xml????
logging:
  level:
    com.xxx.server.mapper: debug
